### ISSUE TITLE
minIndex error

### ISSUE THREAD

**Issue by namikarif** [andrehtissot/cordova-plugin-fcm-image-support#5]
namik@Namiks-MBP CargoDiem Mobil % ionic cordova plugin add cordova-plugin-fcm-image-support
> cordova plugin add cordova-plugin-fcm-image-support
Installing "cordova-plugin-fcm-image-support" for android
Installing "cordova-plugin-fcm-image-support" for ios
cordova-plugin-fcm-image-support depends on Firebase/Messaging, which may conflict with another plugin. Firebase/Messaging@undefined is already installed and was not overwritten.
Running command: pod install --verbose
Adding cordova-plugin-fcm-image-support to package.json
Error: minIndex not found
    at getMinIndex (/Users/namik/Desktop/Namiq/CargoDiem/Mobile/CargoDiem Mobil/plugins/cordova-plugin-fcm-image-support/scripts/configure_main_project_pbxproj.js:35:13)
    at processInsertable (/Users/namik/Desktop/Namiq/CargoDiem/Mobile/CargoDiem Mobil/plugins/cordova-plugin-fcm-image-support/scripts/configure_main_project_pbxproj.js:79:16)
    at main (/Users/namik/Desktop/Namiq/CargoDiem/Mobile/CargoDiem Mobil/plugins/cordova-plugin-fcm-image-support/scripts/configure_main_project_pbxproj.js:100:18)
    at Object.<anonymous> (/Users/namik/Desktop/Namiq/CargoDiem/Mobile/CargoDiem Mobil/plugins/cordova-plugin-fcm-image-support/scripts/configure_main_project_pbxproj.js:113:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  extras: {
    insertable: {
      text: '\n' +
        '\t\t\t\t\t3E7143F024607362001886A3 = {\n' +
        '\t\t\t\t\t\tCreatedOnToolsVersion = 11.3.1;\n' +
        '\t\t\t\t\t\tProvisioningStyle = Automatic;\n' +
        '\t\t\t\t\t};',
      prependAt: '\n\t\t\t\t};',
      within: [Array]
    },
    minIndex: undefined,
    maxIndex: undefined,
    position: undefined,
    appConfig: { mainProductBundleIdentifier: 'com.cargo.diem' }
  }
}

**Comment by vladislavgolubev** [comment]
in the www folder there should be files to copy, at least an empty index.html.
otherwise, the plugin breaks during installation, not finding the section in the project configuration file project.pbxproj, which is responsible for copying files.
